#CRIAÇÃO DE UMA STORED PROCEDURE QUE CONTA E
#RETORNA O NÚMERO TOTAL DE PACIENTES

DELIMITER $

	CREATE PROCEDURE CONTAGEM_PACIENTES(OUT TOTAL_PACIENTES INT(10))
    
		BEGIN
        
			SELECT COUNT(cod_paciente) INTO TOTAL_PACIENTES FROM tbl_paciente;
        
		END
        
$

CALL CONTAGEM_PACIENTES(@TOTAL_PACIENTES);

SELECT @TOTAL_PACIENTES;